services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api

  server:
    image: hello-back-dev
    build:
      context: .
      dockerfile: ./todo-backend/dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - REDIS_URL=redis://todo-app-redis-1:6379
      - MONGO_URL=mongodb://the_username:the_password@todo-app-mongo-1:27017/the_database
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db 

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server