version: '3.8'

services:
  app:
    image: blog-front-dev
    build:
      context: ./bloglist-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
  
  server:
    image: blog-back-dev
    build:
      context: ./bloglist-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3003