version: '3.8'

services:
  app:
    image: blog-front
    build:
      context: ./bloglist-frontend/
      dockerfile: Dockerfile
    ports:
      - 5173:5173
  
  server:
    image: blog-back
    build:
      context: ./bloglist-backend/
      dockerfile: Dockerfile
    ports:
      - 3003:3003